### ISSUE TITLE
Cannot set app notification as sensitive.

### ISSUE THREAD

**Issue by SukantGujar** [adrian-bl-yuga/device-sony-c6603#15]
Sensitive notification option for individual apps in Sound & notification > App notifications > _your app_ is missing. Typically this is available when a PIN/Pattern lock is set. I have a PIN lock, but the Sensitive option is not being displayed. Only "Block" & "Priority" are available.

More information about Sensitive notifications - http://fieldguide.gizmodo.com/keep-your-sensitive-info-off-the-lock-screen-in-android-1660573644. The missing Sensitive option is visible in last image on that post.

**Comment by SukantGujar** [comment]
On further analysis, this option is available only when "Show all notifications" is set. When I chose "Hide sensitive notifications" instead, the "Sensitive" option is no longer visible for any app. With "Show all notifications" set, if I turn Sensitive on for any app, its notifications are hidden even though I have set all notifications to be displayed. 

I think its supposed to work the other way round.

**Comment by AdmiralRedRum** [comment]
Actually, i think you misunderstood it,
1. Show All means show everything unless otherwise stated (for example, you listing them as senstive). So unless you select them as sensitive, everything will be shown, app name & what info it contains. If you choose certain apps as sensitive, those CERTAIN apps will only show app names and hide contents (view example below).
2. Hide All Sensitive means to show the header (the app name that is showing the notification), but hide the info, so, you do NOT get to choose since this will hide all contents, for example,---WHATSAPP - ABC says hello----, so in this case, 'ABC says hello' is the content, and will be hidden, and you will only see ----Whatsapp ---, and in this mode, this function applies to ALL NOTIFICATIONS FROM ALL APPS. Ergo, only APP NAMES will be shown.
3. Do not show at all, means, that nothing will be shown, not even the app name.

**Comment by AdmiralRedRum** [comment]
So as you can see, Android considers all contents as sensitive when you set "Hide all sensitive content" and will only show you the APP NAME.

So if you want to only "filter" or "sensitive" certain apps, use Show ALL, then select the ones you think are sensitive. I've tried it myself.

**Comment by SukantGujar** [comment]
Yep, I get it now, thanks AdmiralRedRum! They should have actually kept only two options Show/Dont show as the value of the Hide sensitive is very little. Closing this issue.
